/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package newsApi;

import com.kwabenaberko.newsapilib.NewsApiClient;
import com.kwabenaberko.newsapilib.models.request.TopHeadlinesRequest;
import com.kwabenaberko.newsapilib.models.response.ArticleResponse;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;



public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        
        NewsApiClient newsApiClient = new NewsApiClient("7a35151e277c485da86cab7e6ea1db53");
        
  
        
     // /v2/top-headlines
newsApiClient.getTopHeadlines(
  new TopHeadlinesRequest.Builder()
    .category("business")
    .country("pl")
    .build(),
  new NewsApiClient.ArticlesResponseCallback() {
    @Override
    public void onSuccess(ArticleResponse response) {
        
        try {
      File myObj = new File("filename.txt");
      if (myObj.createNewFile()) {
        System.out.println("File created: " + myObj.getName());
      } else {
        System.out.println("File already exists.");
      }
    } catch (IOException e) {
      System.out.println("An error occurred.");
    }
        try {
         FileWriter myWriter = new FileWriter("filename.txt");
         
        int i=response.getTotalResults();
        System.out.println(i);
        myWriter.write("iloœæ wszystkich materia³ów "+ i+"\n");
        
        for(int x=0;x<20;x++){
            System.out.println("artyku³ nr: "+(x+1));
            myWriter.write("artyku³ nr: "+(x+1)+"\n");
      System.out.println("tytu³: "+ response.getArticles().get(x).getTitle()+
              "\n : Opis: "+
              response.getArticles().get(x).getDescription()+
              "\n : Auor: "+response.getArticles().get(x).getAuthor() );
     myWriter.write("tytu³: "+ response.getArticles().get(x).getTitle()+
              "\n : Opis: "+
              response.getArticles().get(x).getDescription()+
              "\n : Auor: "+response.getArticles().get(x).getAuthor());
      
        }
         myWriter.close();
      System.out.println("Successfully wrote to the file.");
        
        } catch (IOException e) {
      System.out.println("An error occurred on writing file.");
    }
    }

    @Override
    public void onFailure(Throwable throwable) {
      System.out.println(throwable.getMessage());
    }
  }
);
        
  
        
    }
}
